headers = []

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
headers = { Access-Control-Allow-Origin = "*" }

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
  command = "npm run build"
  publish = "dist/angular-employee-app/browser"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]